/*
 * Srijon Captioner - Premiere ExtendScript timeline bridge.
 * Watches the active project's Srijon Captioner Audio/StylizeBridge folder.
 * The UXP panel owns all transcript intelligence. This bridge only performs
 * Premiere operations that are still more reliable in the legacy scripting DOM:
 * insert MOGRT, write exposed MOGRT parameters, set duration, and replace clips
 * previously generated by Srijon Captioner.
 */

var SrijonStylizeBridge = (function () {
    var VERSION = "1.0.0";
    var processing = false;

    function slash(path) {
        return String(path || "").replace(/\\/g, "/");
    }

    function projectQueueFolder() {
        try {
            if (!app || !app.project || !app.project.path) return null;
            var projectFile = new File(app.project.path);
            var root = projectFile.parent;
            var folder = new Folder(slash(root.fsName) + "/Srijon Captioner Audio/StylizeBridge");
            if (!folder.exists) folder.create();
            return folder.exists ? folder : null;
        } catch (_) {
            return null;
        }
    }

    function readText(file) {
        file.encoding = "UTF-8";
        if (!file.open("r")) throw new Error("Could not open " + file.fsName);
        var text = file.read();
        file.close();
        return text;
    }

    function writeJson(path, value) {
        var file = new File(path);
        file.encoding = "UTF-8";
        if (!file.open("w")) throw new Error("Could not create " + path);
        file.write(JSON.stringify(value, null, 2));
        file.close();
    }

    function timeAt(seconds) {
        var t = new Time();
        t.seconds = Math.max(0, Number(seconds) || 0);
        return t;
    }

    function getProps(component) {
        var out = [];
        if (!component || !component.properties) return out;
        var props = component.properties;
        var n = Number(props.numItems || props.length || 0);
        for (var i = 0; i < n; i++) {
            try { if (props[i]) out.push(props[i]); } catch (_) {}
        }
        return out;
    }

    function findParam(component, displayName) {
        var props = getProps(component);
        var target = String(displayName || "");
        for (var i = 0; i < props.length; i++) {
            try {
                if (String(props[i].displayName || "") === target) return props[i];
            } catch (_) {}
        }
        // Last-resort case-insensitive match for templates exported on hosts that
        // alter controller capitalization.
        var lower = target.toLowerCase();
        for (var j = 0; j < props.length; j++) {
            try {
                if (String(props[j].displayName || "").toLowerCase() === lower) return props[j];
            } catch (_) {}
        }
        return null;
    }

    function mgtComponent(clip) {
        for (var i = 0; i < 25; i++) {
            try {
                var comp = clip && clip.getMGTComponent ? clip.getMGTComponent() : null;
                if (comp) return comp;
            } catch (_) {}
            $.sleep(40);
        }
        return null;
    }

    function setField(component, name, value) {
        var param = findParam(component, name);
        if (!param) return { ok:false, name:name, error:"Exposed MOGRT controller not found" };
        try {
            var rc = param.setValue(String(value == null ? "" : value), 0);
            return { ok:rc === 0 || rc === undefined, name:name, rc:rc };
        } catch (e) {
            return { ok:false, name:name, error:String(e) };
        }
    }

    function removeGenerated(track, prefix) {
        var removed = 0;
        try {
            var clips = track.clips;
            for (var i = Number(clips.numItems || 0) - 1; i >= 0; i--) {
                var clip = clips[i];
                if (clip && String(clip.name || "").indexOf(prefix) === 0) {
                    try {
                        if (clip.remove(0, 0) === 0) removed++;
                    } catch (_) {}
                }
            }
        } catch (_) {}
        return removed;
    }

    function processJob(jobFile) {
        var job = JSON.parse(readText(jobFile));
        var queue = jobFile.parent;
        var startedPath = slash(queue.fsName) + "/" + job.jobId + ".started.json";
        var resultPath = slash(queue.fsName) + "/" + job.jobId + ".result.json";

        writeJson(startedPath, { ok:true, jobId:job.jobId, bridgeVersion:VERSION, startedAt:(new Date()).toUTCString() });

        var seq = app.project.activeSequence;
        if (!seq) throw new Error("No active sequence in Premiere.");
        if (job.sequenceName && String(seq.name || "") !== String(job.sequenceName)) {
            throw new Error("Active sequence changed. Expected '" + job.sequenceName + "', found '" + seq.name + "'.");
        }

        var trackIndex = Math.max(0, Number(job.videoTrackIndex) || 0);
        if (!seq.videoTracks || trackIndex >= Number(seq.videoTracks.numTracks || seq.videoTracks.length || 0)) {
            throw new Error("Target V" + (trackIndex + 1) + " does not exist. Add that video track in Premiere or choose a lower target track.");
        }
        var targetTrack = seq.videoTracks[trackIndex];
        var removed = job.replaceExisting ? removeGenerated(targetTrack, String(job.clipNamePrefix || "SCAP:")) : 0;

        var blocks = job.blocks || [];
        var created = 0;
        var warnings = [];

        for (var i = 0; i < blocks.length; i++) {
            var block = blocks[i];
            var start = timeAt(block.start);
            var clip = seq.importMGT(String(job.mogrtPath), String(start.ticks), trackIndex, 0);
            if (!clip) throw new Error("Premiere could not insert MOGRT block " + (i + 1) + ".");

            try { clip.name = String(block.name || ("SCAP:" + (i + 1))); } catch (_) {}

            var component = mgtComponent(clip);
            if (!component) throw new Error("Inserted MOGRT has no editable MGT component. Re-export the template from After Effects.");

            var fields = block.fields || {};
            for (var key in fields) {
                if (!fields.hasOwnProperty(key)) continue;
                var fieldResult = setField(component, key, fields[key]);
                if (!fieldResult.ok) {
                    warnings.push("Block " + (i + 1) + " / " + key + ": " + fieldResult.error);
                }
            }

            try {
                var end = timeAt(Math.max(Number(block.start) + 0.001, Number(block.end)));
                clip.end = end;
            } catch (durationError) {
                warnings.push("Block " + (i + 1) + ": could not set exact end time (" + durationError + ")");
            }

            created++;
        }

        writeJson(resultPath, {
            ok:true,
            jobId:job.jobId,
            bridgeVersion:VERSION,
            created:created,
            removed:removed,
            warnings:warnings,
            finishedAt:(new Date()).toUTCString()
        });

        try { jobFile.remove(); } catch (_) {}
        return true;
    }

    function failJob(jobFile, error) {
        try {
            var job = JSON.parse(readText(jobFile));
            var path = slash(jobFile.parent.fsName) + "/" + job.jobId + ".result.json";
            writeJson(path, {
                ok:false,
                jobId:job.jobId,
                bridgeVersion:VERSION,
                error:String(error),
                finishedAt:(new Date()).toUTCString()
            });
        } catch (_) {}
    }

    function tick() {
        if (processing) return "busy";
        var queue = projectQueueFolder();
        if (!queue) return "no-project";
        var jobs = queue.getFiles(function (f) {
            return f instanceof File && /\.job\.json$/i.test(f.name);
        });
        if (!jobs || !jobs.length) return "idle";

        jobs.sort(function (a, b) {
            try { return a.modified.getTime() - b.modified.getTime(); } catch (_) { return 0; }
        });

        processing = true;
        try {
            processJob(jobs[0]);
            return "done";
        } catch (e) {
            failJob(jobs[0], e);
            return "error:" + e;
        } finally {
            processing = false;
        }
    }

    return { tick:tick, version:VERSION };
}());
